- name: Download harbor package 
  command: wget https://storage.googleapis.com/harbor-releases/release-1.8.0/harbor-offline-installer-v1.8.1.tgz -O /tmp/harbor.tgz
  args: 
    creates: /tmp/harbor.tgz

- name: Extract harbor.tgz into /tmp/harbor
  unarchive:
    src: /tmp/harbor.tgz
    dest: /tmp
    remote_src: yes
  args: 
    creates: /tmp/harbor

- template:
    src: openssl.cnf.j2
    dest: /etc/ssl/openssl.cnf
    owner: root
    group: root
    mode: 0777

- template:
    src: harbor.yml.j2
    dest: /tmp/harbor/harbor.yml
    owner: root
    group: root
    mode: 0777

- name: docker restart
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Install harbor with clair
  shell: /tmp/harbor/install.sh --with-clair
  args:
    chdir: /tmp/
    creates: harbor-install.log

- name: Log into harbor registry and force re-authorization
  docker_login:
    registry_url: "{{ registry[0] }}"
    username: admin
    password: Harbor12345
    reauthorize: yes
  vars:
    registry:
      - "http://{{ inventory_hostname }}:80"