all:
  vars:
    ansible_ssh_user: matheus
    harbor_admin: cncfdemo
    cert_domain_name: registry.cncf.raj.ninja
    cert_admin_email: matheus@nanoshots.com.br
  children:
    kubernetes:
      children: 
        masters:
          vars:
            linkerd_url: linkerd.raj.ninja
          hosts:
            35.222.8.145:
        nodes:
          hosts:
            34.69.42.57:
            35.222.74.99:
            34.66.110.135:
    harbor:
      hosts:
        34.71.192.242

    front-proxy:
      hosts:
        35.184.92.133: