all:
  vars:
    ansible_ssh_user: matheus
    harbor_admin: cncfdemo
    cert_domain_name: registry.cncf.raj.ninja
    cert_admin_email: matheus@nanoshots.com.br
  children:
    kubernetes:
      children: 
        masters:
          vars:
            linkerd_url: linkerd.raj.ninja
          hosts:
            35.225.145.103:
        nodes:
          hosts:
            34.72.181.46:
            35.193.1.28:
            34.68.114.183:
    harbor:
      hosts:
        34.71.192.242

    front-proxy:
      hosts:
        35.184.92.133: