all:
  children:
    kubernetes:
      children:
        masters:
          hosts:
            3.88.86.155:
        nodes:  
          hosts:
            3.89.206.121:
            54.145.107.35:
    # argo:
      # hosts:
      #   0.0.0.0:
    gitea:
      hosts:
        54.172.158.32:
    # drone:
      # hosts:
      #   0.0.0.0:
    harbor:
      hosts:
        54.209.34.100:
    # kubernetes-masters:
      # hosts:
      #   0.0.0.0:
    # kubernetes-nodes:
      # hosts:
      #   0.0.0.0:
    # test:
      # hosts:
      #   0.0.0.0: