all:
  children:
    kubernetes:
      children:
        masters:
          hosts:
            3.91.235.36:
        nodes:  
          hosts:
            54.198.60.44:
            35.171.151.61:
    # argo:
      # hosts:
      #   0.0.0.0:
    gitea:
      hosts:
        0.0.0.0:
    # drone:
      # hosts:
      #   0.0.0.0:
    harbor:
      hosts:
        0.0.0.0:
    # kubernetes-masters:
      # hosts:
      #   0.0.0.0:
    # kubernetes-nodes:
      # hosts:
      #   0.0.0.0:
    # test:
      # hosts:
      #   0.0.0.0: