  
- pip:
    name:
      - docker

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a

- name: update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - docker.io

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0777'

- template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0777

- file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- name: force systemd to reread configs
  systemd: daemon_reload=yes

# Docker service is disabled by default
- name: enable Docker service
  systemd:
    name: docker
    enabled: yes