- name: Create argocd deployment file
  template:
    src: argo.yaml.j2
    dest: /tmp/argo.yaml
    owner: root
    group: root
    mode: 0777

- name: create argo-cd namespace
  shell: kubectl create namespace argocd
  args:
    chdir: /tmp
    creates: argo-namespace.log

- name: deploy argo-cd 
  shell: kubectl apply -n argocd -f /tmp/argo.yaml
  args:
    chdir: /tmp
    creates: argo-deployment.log